language: generic
sudio: required
services: 
  - docker

before_install:
  - docker build -t cynthia/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cynthia/docker-react npm run test
