language: generic
sudio: required
services: 
  - docker

before_install:
  - docker build -t cynthia/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cynthia/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-186416302941"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  

  
